### ISSUE TITLE
Ensure Galaxy can be run under a URL path prefix.

### ISSUE THREAD

**Issue by nuwang** [CloudVE/galaxy-helm#13]

**Comment by afgane** [comment]
Just a note that we will likely still need to revisit this in the future to support arbitrary prefix vs. only `/galaxy`.

**Comment by nuwang** [comment]
> Just a note that we will likely still need to revisit this in the future to support arbitrary prefix vs. only `/galaxy`.

Won't setting the ingress to an arbitrary path solve that?

**Comment by afgane** [comment]
I was thinking more from the CloudMan/Launch standpoint of being able to assign the prefix at runtime but we should actually move that into its own issue.
