### ISSUE TITLE
Make use of the new Galaxy Helm chart within CloudMan

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#15]
Make CloudMan 2.0 use the Galaxy Helm chart available at
https://github.com/CloudVE/galaxy-kubernetes/tree/v3/galaxy

**Comment by afgane** [comment]
First pass available in https://github.com/galaxyproject/cloudman/commit/dff1a158348c303a32c36ac2724b51fa41cd2c55

**Comment by nuwang** [comment]
This is working as expected now, and new launches use the latest chart.
