### ISSUE TITLE
Enable data persistence via CloudMan

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#17]
Email text from @nuwang: 

I've been looking into the various storage options for Kubernetes. Have looked into a fair number of options, including the AWS EBS dynamic provisioner, Amazon EFS, NFS provisioner, OpenEBS, iSCSI, longhorn, Amazon Storage gateway etc.

The essence of the problem boils down to what is the "best" way to handle storage on Kubernetes. The answer appears to boil down to two principles.
   1. Nodes in Kubernetes work best when they are stateless. Avoid state as much as possible. 
   2. If we do use storage, avoid hostPaths (or any kind of storage that's tied to a particular node) at all cost. Instead, always prefer dynamic provisioners through storage classes. The reason for this is that in the event of a node failure, a dynamic provisioner can detach the disk and reattach it to a new node, thus allowing a stateful set, such as say a database, to recover from faults.

Keeping these two things in mind, the ideal scenario for us is to use storage like CVMFS (already done), and let galaxy use s3 buckets (not done), so that it doesn't matter which node is requesting the data, or how pods are rescheduled - the data is always available. However, no matter what we do, we cannot use s3 buckets for the database, nor can we use NFS, which is not performant. For databases, the best option would be to use block storage devices through say, the EBS provisioner.

In addition, since we do not yet support bucket driven data for Galaxy, and we may need to support other apps like SMRT Portal, RStudio etc., the only available option for us when it comes to shared user data is the NFS dynamic provisioner. The NFS dynamic provisioner can in turn be linked to a dynamically provisioned EBS volume as a backing store, which allows to solve that problem pretty neatly - if the backing EBS node fails, it can be reattached to another node. In the longer term, we could also use something like csi-s3 (https://github.com/ctrox/csi-s3), to handle individual user data by storing them in buckets, and use NFS over EBS for shared project level data.

However, to get the EBS provisioner working on a custom kube cluster (such as rancher) requires a little bit of work. For starters, we need to set a flag so that the cluster is identified as an "Amazon" cluster, which is easy enough. We then also need an IAM policy so that each node can attach storage by itself (https://blog.scottlowe.org/2018/09/28/setting-up-the-kubernetes-aws-cloud-provider/). The requirements for GCE etc. are similar.

Of course, if we use the native cloud provider to provision the cluster (instead of rancher), these settings should come preconfigured, although I didn't get a chance to test it. However, the issue here is that, the level of support offered by OpenStack is completely indeterminate. I did see that NeCTAR now offers a natively provisioned kube cluster, but only on QRISCloud. I didn't actually try it out.

The second situation where this won't work well is with manually provisioned clusters on bare-metal hosts or on non-cloud infrastructure. Here, there is no cloud-EBS to rely on anyway. This is where stuff like iSCSI, OpenEBS, Rook (Ceph) etc. come into play. You can either create storage by pooling existing kube storage, or by using an external storage system which directly exposes itself as iSCSI.

The conclusion appears to be that, to deal with this wide range of use cases, we should make storage as configurable as possible by the administrator/deployer. The easiest way to do this is to use well-defined storage classes. Then, the administrator is free to "implement" those storage classes however they see fit. Storage classes are always dynamically provisioned, and thus, fits with the afore-mentioned principles of kubernetes.

However, since we want a working cluster from the get go, we should define sensible storage classes that work from the get go on the cloud. For other scenarios, we may need an optional dialogue, either in cloudlaunch, or in cloudman, which prompts you to define these storage classes so that the deployment can continue.

Therefore, the specific tasks we need to do are:

1. Test how rancher can be configured for each of the 4 clouds.

For AWS, the procedure is to select the "Cloud provider" as Amazon (see screenshot), define an IAM policy for the node (Configuring AWS EBS for kubernetes
https://blog.scottlowe.org/2018/09/28/setting-up-the-kubernetes-aws-cloud-provider/), defining an IAM role attached to the policy, and then assigning that IAM role to the instance. We need to repeat that process for other clouds.

2. Modify cloudlaunch, cm-boot and cloudman so that these policies and settings are automatically applied when the instance boots up, or any additional cluster nodes are added. Again, this means determining how to do this for each cloud.

As a side note, we should probably be using some native "operator" or autoscaling feature to scale nodes up and down too, so that it's more reactive and works towards reaching a "target state" as opposed to the current way that cloudman does it.

*References*

General performance comparison
https://medium.com/vescloud/kubernetes-storage-performance-comparison-9e993cb27271

Configuring AWS EBS for kubernetes
https://blog.scottlowe.org/2018/09/28/setting-up-the-kubernetes-aws-cloud-provider/

IAM policy
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/cloud-providers/

Configure Openstack
https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/openstack/

Configuring GCE
https://github.com/rancher/rke/issues/1329
https://gist.github.com/thxCode/bb492120ffac07acd78dd6bac462b3f3

**Comment by afgane** [comment]
IAM role assignment implementation for AWS: https://github.com/galaxyproject/cloudlaunch/commit/24ac615b175e632c2b5269e5b6d4b0a1eec13d42

**Comment by afgane** [comment]
- [ ] Test Azure

Otherwise, this is now implemented. One scenario that is not currently supported is the ability to shut down a cluster and start it back up while specifying an existing PVC. The Galaxy Helm chart has an option to supply a PVC at launch but the CloudMan would need to be extended to store the PVC ID somewhere and be able to retrieve it/supply it to CloudLaunch during launch time. For the time being, this is left as a future feature.

**Comment by nuwang** [comment]
An existing thread on restoring PVCs: https://github.com/kubernetes/kubernetes/issues/67138

**Comment by nuwang** [comment]
So it looks to me like perhaps we should be using backup/restore for this instead. On cluster terminate, we can offer the user a choice to backup/archive their cluster, and offer an option to restore state after launching a fresh new cluster.
Two solutions:
1. https://velero.io/docs/v1.0.0/index.html
2. https://appscode.com/products/stash/

**Comment by nuwang** [comment]
Closing this as there's a new issue to track backup/restore: https://github.com/galaxyproject/cloudman/issues/98
