### ISSUE TITLE
Move shed_tool_conf.xml and tool_conf.xml into ConfigMaps

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#22]
Using the tool confs from the CVMFS makes it difficult to make any changes to the list of available tools for the chart users so making a ConfigMap for each of those files would increase configurability. It would also help avoid ghost updates then changes are made to the CVMFS. The downside is that any new tools installed onto the CVMFS will not be included in the future so some tracking/syncing mechanism would be nice.

**Comment by almahmoud** [comment]
tool_conf.xml through configmaps done in https://github.com/CloudVE/galaxy-kubernetes/pull/34.
For shed_tool_conf.xml, given that the one on CVMFS is 18,000+ lines, if we add it to configmaps it would kind of have to be through another file, which would make editing it still hard in cloudman, so not sure what a good answer is for that

**Comment by almahmoud** [comment]
Should we close this, or do we still want a copy of `shed_tool_conf.xml` from CVMFS in the values file?

**Comment by afgane** [comment]
During the weekly Federated Galaxy call a decision was made not to include the ~18,000 line `shed_tool_conf.xml` in the chart. While this limits the configurability of tools within the chart, we can always revisit the topic after we receive some feedback on potential use cases.
