### ISSUE TITLE
Move the sensitive configs from values.yaml into secrets

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#26]

**Comment by almahmoud** [comment]
@nuwang  and I briefly discussed this along with the database scripts changes in this PR: https://github.com/CloudVE/galaxy-kubernetes/pull/27
One topic was whether it's worth leaving some in config maps for settings that are not sensitive and others making secrets, vs doing only secrets to keep it simple and not have two separate types of configs.
It wouldn't be hard to implement having both, the only big difference will be that we will have to add a new nesting under configs to distinguish between the two. Something like `.Values.configs.secrets` and `.Values.configs.configmaps`. We thought it's not worth it for now to keep things simple, but documenting that decision here in case someone else wants to give their thoughts.

**Comment by afgane** [comment]
Following a verbal discussion, it was decided to either use secrets for basically all the config maps (e.g., production deployment) or not (e.g., dev mode). One usability downside when using the secrets is that they are opaque in any dashboard making edits cumbersome at best (e.g., have to decode the value, modify it, and encode it again before applying it). Note that the values stored as secrets can still be inspected by anyone having access to the appropriate dashboard quite easily, just not modified. With that, the thinking was that for production settings, changes should be tracked so a configuration change would basically require a modification of the value in the chart followed by a deployment update. This has the benefit of tracking any changes to a deployment. 
Meanwhile, for the dev mode, all values are visible and easily modifiable via a dashboard. 

This was largely implemented in https://github.com/CloudVE/galaxy-kubernetes/commit/dc223d92991cbd06b1436d61468422b2905a5538.
